# Doesn't work yet, possibly related to https://github.com/signalfx/maestro-ng/issues/63#issuecomment-118337874

__maestro:
  schema: 2

name: demo
ship_defaults:
  api_version: auto
ships:
  vm1:
    ip: 192.168.50.101
    ssh_tunnel:
      user: vagrant
      key: {{ env.HOME }}/.vagrant.d/insecure_private_key
  vm2:
    ip: 192.168.50.102
    ssh_tunnel:
      user: vagrant
      key: {{ env.HOME }}/.vagrant.d/insecure_private_key
services:
  flask-nanoservice:
    image: smoll/flask-nanoservice
    instances:
      flask-nanoservice-1:
        ship: vm1
        ports: {hello: "5000:5001"}
      flask-nanoservice-2:
        ship: vm2
        ports: {hello: "5000:5002"}
