# Doesn't work yet, possibly related to https://github.com/signalfx/maestro-ng/issues/63#issuecomment-118337874

__maestro:
  schema: 2

name: flask-nanoservice
ships:
  vm1:
    ip: 192.168.50.101
    ssh_tunnel:
      user: core
      key: {{ env.HOME }}/.vagrant.d/insecure_private_key
  vm2:
    ip: 192.168.50.102
    ssh_tunnel:
      user: core
      key: {{ env.HOME }}/.vagrant.d/insecure_private_key
services:
  hello:
    image: smoll/flask-nanoservice
    instances:
      f1:
        ship: vm1
        ports: {http: "5000:5001"}
      f2:
        ship: vm2
        ports: {http: "5000:5002"}
