# Ansible playbook for deploying the app container

- name: Deploy
  hosts: apphosts
  tasks:
    - name: Flask nanoservice
      # TODO: get rid of sudo
      sudo: yes
      docker:
        name: flask-nanoservice
        image: smoll/flask-nanoservice:latest
        publish_all_ports: yes
        pull: always
        state: reloaded
