# Ansible playbook for app container

- name: Flask nanoservice
  docker:
    name: flask-nanoservice
    image: smoll/flask-nanoservice:latest
    pull: always
    state: reloaded
    restart_policy: always
