- name: Install components common to all hosts
  hosts: all
  roles:
    # Install Docker
    - ansible-docker
    # Dependency for Ansible `docker` module/primitive
    - bobbyrenwick.pip
  tasks:
    # Workaround for https://github.com/ansible/ansible-modules-core/issues/1792#issuecomment-148264962
    - name: make sure required PyPi packages are installed
      pip: name={{ item }} state=present
      sudo: yes
      with_items:
        - docker-py==1.2.3
        - six>=1.4.0
